project:
  type: website
  output-dir: docs

website:
  title: "Denis Abdullin"
  navbar:
   background: primary
   left:
     - index.qmd
     - blog.qmd

format:
  html:
    theme:
      light: zephyr
      dark: cyborg
    css: styles.css

editor: visual
